### PR TITLE
Added calculating average roll to .parse function

### PR DESCRIPTION
**Pull request by gsheppard**

### CODE REVIEW

**Comment by thebinarypenguin** [comment]
I don't really see a use for this feature. Care to elaborate?

**Comment by gsheppard** [comment]
I'm working on a project for D&D Monster management (think D&D Fight Club for iOS or Fantasy Grounds for Steam if you've ever used or heard of them, but browser based and on a db, so more cross-platform).

I found droll and love it, but noticed it doesn't do averages which are used heavily when detailing monsters' HP and features. Figured I would add it and make a PR since droll didn't have it.

**Comment by thebinarypenguin** [comment]
OK I'm on board but how about instead of `average` you add a `minResult`, `maxResult`, and `avgResult` that way it's easier for the user to display either a range or the average?

Also does that formula really calculate the average? Perhaps you're taking a mathematical shortcut I'm not seeing.

Also Also I see that using the variable name `result` in the `parse()` function was a bad choice if you wanted to you could change it to `formula` (or I'll change it before I publish to npm)

**Comment by thebinarypenguin** [comment]
oh and just a reminder we'll have to update the documentation in the README.md too

**Comment by thebinarypenguin** [comment]
@gsheppard since I didn't get a response from you I'm going to implement the changes myself (probably tonight) and track the work using issue #3

**Comment by gsheppard** [comment]
@thebinarypenguin Hey I'm sorry. Started a new job pretty much right after submitting this and it took over the bulk of my time and creative energies. I'm glad you implemented it!

**Pull request closed without merging**
